code4romania/expert-consultation-api

src/main/java/com/code4ro/legalconsultation/models/DocumentMetadata.java
src/main/java/com/code4ro/legalconsultation/models/DocumentType.java

I created a data model for the document's metadata with equivalent types. Also created models package.
Issue #5

Created DocumentMetadata entity

---

.travis.yml
README.md
etc/docker/Dockerfile-dev
etc/docker/README.md
etc/docker/docker-compose-dev.yml

* prepare a deploy docker image that takes the ci build result package and runs it

add travis ci

---

src/main/java/com/code4ro/legalconsultation/service/api/StorageApi.java
src/main/java/com/code4ro/legalconsultation/service/impl/AmazonS3StorageService.java
src/main/java/com/code4ro/legalconsultation/service/impl/FilesystemStorageService.java
src/test/java/com/code4ro/legalconsultation/service/AmazonS3StorageServiceTest.java

Added implementation and test
@mihairinzis please review
issue #72

Add the possibility to delete files #72

---

src/main/resources/application-production.yml

Modify the configuration attributes to be passed to a Docker container as parameters.

Modify config for AWS credentials

---

src/main/java/com/code4ro/legalconsultation/service/impl/MailService.java
src/test/java/com/code4ro/legalconsultation/util/RandomObjectFiller.java

fixes https://github.com/code4romania/expert-consultation-api/issues/89

Test object filler: do not generate empty strings for fields

---

etc/docker/docker-compose-prod.yml
src/test/java/com/code4ro/legalconsultation/util/RandomObjectFiller.java

fixes https://github.com/code4romania/expert-consultation-api/issues/105

Set MySQL server charset and collation to UTF-mb4

---

src/main/java/com/code4ro/legalconsultation/controller/DocumentController.java
src/main/java/com/code4ro/legalconsultation/model/DocumentUserAssignmentDto.java
src/main/java/com/code4ro/legalconsultation/model/persistence/DocumentConsolidated.java
src/main/java/com/code4ro/legalconsultation/service/api/DocumentService.java
src/main/java/com/code4ro/legalconsultation/service/impl/DocumentServiceImpl.java
src/main/java/com/code4ro/legalconsultation/service/impl/UserService.java
src/test/java/com/code4ro/legalconsultation/service/DocumentServiceTest.java

Assign users to documents

---

src/main/resources/application-production.yml
src/main/resources/application.yml

This change is required to solve: https://github.com/code4romania/expert-consultation-api/issues/109

add character encoding UTF-8 to DB connection property

---

src/main/java/com/code4ro/legalconsultation/controller/DocumentController.java
src/main/java/com/code4ro/legalconsultation/service/impl/DocumentConsolidatedService.java
src/main/java/com/code4ro/legalconsultation/service/impl/DocumentServiceImpl.java
src/test/java/com/code4ro/legalconsultation/service/DocumentConsolidatedServiceTest.java
src/test/java/com/code4ro/legalconsultation/service/DocumentServiceTest.java

Update id handling of documents (between metadata and consolidated)

Assign users to documents fixes

---

src/main/java/com/code4ro/legalconsultation/service/impl/MailService.java
src/main/resources/application-production.yml
src/main/resources/application.yml
src/test/java/com/code4ro/legalconsultation/service/MailServiceTest.java
src/test/resources/application.yml

AWS SES server usage with SMTP

Add AWS SES server for email sending

---

src/main/java/com/code4ro/legalconsultation/controller/FileController.java

Fix documentation issue in FileController

---

src/main/java/com/code4ro/legalconsultation/controller/UserController.java
src/main/java/com/code4ro/legalconsultation/converters/UserMapper.java
src/main/java/com/code4ro/legalconsultation/service/impl/UserService.java
src/test/java/com/code4ro/legalconsultation/controller/UserControllerIntegrationTest.java

Implemented using spring data jpa's query by example

Added user filtering

---

src/main/java/com/code4ro/legalconsultation/controller/DocumentController.java
src/main/java/com/code4ro/legalconsultation/converters/PdfHandleMapper.java
src/main/java/com/code4ro/legalconsultation/model/dto/PdfHandleDto.java
src/main/java/com/code4ro/legalconsultation/model/persistence/PdfHandle.java
src/main/java/com/code4ro/legalconsultation/repository/PdfHandleRepository.java
src/main/java/com/code4ro/legalconsultation/service/api/DocumentService.java
src/main/java/com/code4ro/legalconsultation/service/api/PDFService.java
src/main/java/com/code4ro/legalconsultation/service/impl/DocumentServiceImpl.java
src/main/java/com/code4ro/legalconsultation/service/impl/pdf/PDFServiceImpl.java
src/test/java/com/code4ro/legalconsultation/controller/DocumentControllerIntegrationTest.java
src/test/java/com/code4ro/legalconsultation/service/DocumentServiceTest.java
src/test/java/com/code4ro/legalconsultation/service/PdfServiceTest.java

Fix #127 
I know integration tests should be written, but right know I would like to know what the maintainers think about this.

Implement upload pdf document

---

src/main/java/com/code4ro/legalconsultation/controller/VoteController.java
src/main/java/com/code4ro/legalconsultation/model/dto/VoteDto.java
src/main/java/com/code4ro/legalconsultation/model/persistence/Vote.java
src/main/java/com/code4ro/legalconsultation/model/persistence/VoteType.java
src/main/java/com/code4ro/legalconsultation/repository/VoteRepository.java
src/main/java/com/code4ro/legalconsultation/service/api/CommentService.java
src/main/java/com/code4ro/legalconsultation/service/api/DocumentNodeService.java
src/main/java/com/code4ro/legalconsultation/service/api/VoteService.java
src/main/java/com/code4ro/legalconsultation/service/impl/CommentServiceImpl.java
src/main/java/com/code4ro/legalconsultation/service/impl/VoteServiceImpl.java
src/test/java/com/code4ro/legalconsultation/service/impl/VoteServiceImplGetAllTest.java
src/test/java/com/code4ro/legalconsultation/service/impl/VoteServiceImplSaveOrUpdateTest.java

- votes can be: up, down, abstain
- each user has at most 1 vote per section
- user can see all votes for document nodes anonymously, and his own votes with his id
- TODO: an admin can open and close the voting period for a documen
- added unit tests

[66][Documents] Implement voting feature for document sections

---

src/main/resources/application-production.yml

Update production configuration for using AWS SES email.

Update prod config

---

src/main/java/com/code4ro/legalconsultation/user/model/dto/UserDto.java
src/main/java/com/code4ro/legalconsultation/user/model/persistence/User.java
src/main/java/com/code4ro/legalconsultation/user/model/persistence/UserSpecialization.java
src/main/java/com/code4ro/legalconsultation/user/service/UserService.java
src/test/java/com/code4ro/legalconsultation/user/service/UserServiceTest.java

gave #180 a shot, let me know what you think
* specialization as enum (demo list of values, should be updated)
* supported through csv import flow
* searchable (exact match)
* tests

added specialization to user model

---

src/main/java/com/code4ro/legalconsultation/document/consolidated/model/dto/DocumentConsolidatedDto.java
src/main/java/com/code4ro/legalconsultation/document/consolidated/model/dto/DocumentConsultationDataDto.java
src/main/java/com/code4ro/legalconsultation/document/consolidated/model/persistence/DocumentConsolidated.java
src/main/java/com/code4ro/legalconsultation/document/core/controller/DocumentController.java
src/main/java/com/code4ro/legalconsultation/document/core/service/DocumentService.java
src/main/java/com/code4ro/legalconsultation/document/core/service/impl/DocumentServiceImpl.java
src/main/java/com/code4ro/legalconsultation/user/model/dto/UserDto.java
src/test/java/com/code4ro/legalconsultation/document/core/controller/DocumentControllerIntegrationTest.java

Backend for https://github.com/code4romania/expert-consultation-client/issues/106 
adds extra fields to the consultation document representing start date, deadline and consultation flag
via UI + created test in IntegrationTest class of DocumentController

Add consultation data to document

---

.github/workflows/build.yml
src/main/java/com/code4ro/legalconsultation/document/core/controller/DocumentController.java
src/main/java/com/code4ro/legalconsultation/storage/service/impl/FilesystemStorageService.java
src/test/java/com/code4ro/legalconsultation/user/controller/UserControllerIntegrationTest.java

Fix failing tests

---

src/main/java/com/code4ro/legalconsultation/comment/mapper/CommentDocumentDataMapper.java
src/main/java/com/code4ro/legalconsultation/comment/mapper/CommentMapper.java
src/main/java/com/code4ro/legalconsultation/comment/model/dto/CommentDetailDto.java
src/main/java/com/code4ro/legalconsultation/comment/service/impl/CommentServiceImpl.java
src/main/java/com/code4ro/legalconsultation/document/core/service/DocumentService.java
src/main/java/com/code4ro/legalconsultation/document/core/service/impl/DocumentServiceImpl.java
src/test/java/com/code4ro/legalconsultation/comment/controller/CommentsControllerTest.java
src/test/java/com/code4ro/legalconsultation/comment/controller/DocumentCommentsControllerIntegrationTest.java

Closes #201 
Added the fields specified in the ticket to the data retrieved from the /pending endpoint
There is a Controller test, also tested via UI.
Known issues: there is an n+1 happening when loading the extra data for comments, but there is extra work needed in order to improve the whole loading process so this should be done with another ticket.

201 modify pending comment endpoint to retrieve node data

---

src/main/java/com/code4ro/legalconsultation/user/controller/UserController.java

Closes #105 
Through the UI, when adding a member, the list of specializations should be the same with the enum in the backend.

105 endpoint to retrieve user specializations

---

README.md
src/main/java/com/code4ro/legalconsultation/authentication/config/AuthConfiguration.java
src/main/java/com/code4ro/legalconsultation/authentication/service/ApplicationUserService.java
src/main/java/com/code4ro/legalconsultation/core/config/SwaggerConfiguration.java
src/test/java/com/code4ro/legalconsultation/authentication/config/AuthConfigurationTest.java
src/test/java/com/code4ro/legalconsultation/user/controller/UserControllerIntegrationTest.java

Creates a default admin:admin user for local development, when no other users exist.
Closes #204 
Tested on local environment when:
- no users existed
- there was one other user present

#204 Added admin user intialization for dev profile

---

src/main/java/com/code4ro/legalconsultation/comment/controller/DocumentCommentsController.java
src/main/java/com/code4ro/legalconsultation/comment/mapper/CommentDocumentDataMapper.java
src/main/java/com/code4ro/legalconsultation/comment/mapper/CommentMapper.java
src/main/java/com/code4ro/legalconsultation/comment/model/dto/CommentDetailDto.java
src/main/java/com/code4ro/legalconsultation/comment/model/dto/CommentForChatDto.java
src/main/java/com/code4ro/legalconsultation/comment/model/dto/CommentWithUserDto.java
src/main/java/com/code4ro/legalconsultation/comment/model/persistence/Comment.java
src/main/java/com/code4ro/legalconsultation/comment/service/impl/CommentServiceImpl.java
src/main/java/com/code4ro/legalconsultation/document/consolidated/service/DocumentConsolidatedService.java
src/main/java/com/code4ro/legalconsultation/document/core/controller/DocumentController.java
src/main/java/com/code4ro/legalconsultation/document/core/service/DocumentService.java
src/main/java/com/code4ro/legalconsultation/document/core/service/impl/DocumentServiceImpl.java
src/main/java/com/code4ro/legalconsultation/invitation/repository/InvitationRepository.java
src/main/java/com/code4ro/legalconsultation/security/service/CurrentUserService.java
src/main/java/com/code4ro/legalconsultation/security/service/impl/SpringCurrentUserService.java
src/main/java/com/code4ro/legalconsultation/user/controller/UserController.java
src/main/java/com/code4ro/legalconsultation/vote/controller/VoteController.java
src/main/java/com/code4ro/legalconsultation/vote/model/dto/VoteDto.java
src/main/java/com/code4ro/legalconsultation/vote/repository/VoteRepository.java
src/main/java/com/code4ro/legalconsultation/vote/service/VoteService.java
src/main/java/com/code4ro/legalconsultation/vote/service/impl/VoteServiceImpl.java
src/test/java/com/code4ro/legalconsultation/comment/controller/DocumentCommentsControllerIntegrationTest.java
src/test/java/com/code4ro/legalconsultation/comment/service/CommentServiceTest.java
src/test/java/com/code4ro/legalconsultation/core/controller/AbstractControllerIntegrationTest.java
src/test/java/com/code4ro/legalconsultation/document/core/service/DocumentServiceTest.java
src/test/java/com/code4ro/legalconsultation/security/service/CurrentUserServiceTest.java
src/test/java/com/code4ro/legalconsultation/vote/service/VoteServiceImplGetAllTest.java
src/test/java/com/code4ro/legalconsultation/vote/service/VoteServiceImplSaveOrUpdateTest.java

API updates for comment votes: add your vote and total number of votes to the list of comments for a document node.
Closes code4romania/expert-consultation-client#116
With Postman in following scenarios:
- comments API: 0, 1 and 2 comments, with and without votes
- vote API: create a new vote, create a vote when it already exists (it should get updated), update existing vote

code4romania/expert-consultation-client#116 Started work on comment votes

---

pom.xml
src/main/java/com/code4ro/legalconsultation/core/config/JpaConfiguration.java
src/main/java/com/code4ro/legalconsultation/core/config/MiscellaneousConfiguration.java
src/main/java/com/code4ro/legalconsultation/core/model/persistence/ShedLock.java
src/main/java/com/code4ro/legalconsultation/document/configuration/model/persistence/DocumentConfiguration.java
src/main/java/com/code4ro/legalconsultation/document/consolidated/repository/DocumentConsolidatedRepository.java
src/main/java/com/code4ro/legalconsultation/document/consolidated/repository/QueryDslDocumentConsolidatedRepository.java
src/main/java/com/code4ro/legalconsultation/document/consolidated/repository/QueryDslDocumentConsolidatedRepositoryImpl.java
src/main/java/com/code4ro/legalconsultation/mail/config/MailConfiguration.java
src/main/java/com/code4ro/legalconsultation/mail/scheduler/MailScheduler.java
src/main/java/com/code4ro/legalconsultation/mail/service/MailApi.java
src/main/java/com/code4ro/legalconsultation/mail/service/impl/MailService.java
src/main/resources/i18n/messages.properties
src/main/resources/i18n/messages_ro.properties
src/main/resources/templates/document-assigned-email-ro.ftl
src/main/resources/templates/document-consultation-email-en.ftl
src/main/resources/templates/document-consultation-email-ro.ftl

Sends e-mails to assigned document users when consultation period starts.
Closes #123 
Cron job tested locally with a demo frequency, validating subject and email content.
Tested on 1 document with 2 assigned users.
E-mail body tested with online testing tool (https://putsmail.com/) and Gmail.
Known issues: Code4Ro image is not supported. PNG needed.

#123 Send mails when document goes into consultation
